name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas matplotlib tqdm numpy gitdir
        
    - name: Downloading CDC Models from ForecastHub
      run: |
        ls
        python -m gitdir https://github.com/reichlab/covid19-forecast-hub/tree/master/data-processed
    - name: Processing Data
      run: |
        python scripts/process_cdc.py
      
      python scripts/process_cdc.py
